#!/usr/bin/env node
/**
 * Generates lib/styles/tokens.css from the `tokens` section of motion-system.json.
 *
 *   node website-template/scripts/build-tokens.mjs
 *
 * Naming: colours and layout → --<key>, easings → --ease-<key>, durations → --dur-<key>.
 * Dark values go on :root (the default theme) and light values on [data-theme="light"].
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specPath = join(here, "..", "motion-system.json");
const outPath = join(here, "..", "lib", "styles", "tokens.css");

const { tokens } = JSON.parse(readFileSync(specPath, "utf8"));

const block = (selector, entries, extra = []) =>
  [`${selector} {`, ...entries.map(([name, value]) => `  --${name}: ${value};`), ...extra.map((line) => `  ${line}`), "}"].join("\n");

const vars = (map, prefix = "") => Object.entries(map).map(([key, value]) => [`${prefix}${key}`, value]);

const root = [
  ...vars(tokens.color.dark),
  ...vars(tokens.layout),
  ...Object.entries(tokens.easing).map(([key, e]) => [`ease-${key}`, e.css]),
  ...Object.entries(tokens.duration).map(([key, d]) => [`dur-${key}`, d.css]),
];

const css = [
  "/* Generated by scripts/build-tokens.mjs from motion-system.json. Do not edit by hand. */",
  "",
  block(":root", root, ["color-scheme: dark;"]),
  "",
  block('[data-theme="light"]', vars(tokens.color.light), ["color-scheme: light;"]),
  "",
].join("\n");

writeFileSync(outPath, css);
console.log(`Wrote ${root.length + Object.keys(tokens.color.light).length} tokens to ${outPath}`);
